# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/SABER_FPGA/project_1/project_1.srcs/sources_1/bd/Top/ip/Top_zynq_ultra_ps_e_0_0_1/Top_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'Top_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SABER_FPGA/project_1/project_1.srcs/sources_1/bd/Top/ip/Top_zynq_ultra_ps_e_0_0_1/Top_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/SABER_FPGA/project_1/project_1.srcs/sources_1/bd/Top/ip/Top_zynq_ultra_ps_e_0_0_1/Top_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/SABER_FPGA/project_1/project_1.srcs/sources_1/bd/Top/ip/Top_zynq_ultra_ps_e_0_0_1/Top_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'Top_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SABER_FPGA/project_1/project_1.srcs/sources_1/bd/Top/ip/Top_zynq_ultra_ps_e_0_0_1/Top_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/SABER_FPGA/project_1/project_1.srcs/sources_1/bd/Top/ip/Top_zynq_ultra_ps_e_0_0_1/Top_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
