# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/INS_RAM/INS_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INS_RAM || ORIG_REF_NAME==INS_RAM} -quiet] -quiet

# IP: ip/BRAM64_1024/BRAM64_1024.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM64_1024 || ORIG_REF_NAME==BRAM64_1024} -quiet] -quiet

# Block Designs: bd/Top/Top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top || ORIG_REF_NAME==Top} -quiet] -quiet

# IP: bd/Top/ip/Top_zynq_ultra_ps_e_0_0_1/Top_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Top_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_AXI_Slave8Ports_0_0/Top_AXI_Slave8Ports_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_AXI_Slave8Ports_0_0 || ORIG_REF_NAME==Top_AXI_Slave8Ports_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_ps8_0_axi_periph_0/Top_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_ps8_0_axi_periph_0 || ORIG_REF_NAME==Top_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/Top/ip/Top_rst_ps8_0_99M_0/Top_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_rst_ps8_0_99M_0 || ORIG_REF_NAME==Top_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/Top/ip/Top_ComputeCoreWrapper_0_0/Top_ComputeCoreWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_ComputeCoreWrapper_0_0 || ORIG_REF_NAME==Top_ComputeCoreWrapper_0_0} -quiet] -quiet

# IP: ip/INS_RAM/INS_RAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INS_RAM || ORIG_REF_NAME==INS_RAM} -quiet] -quiet

# IP: ip/BRAM64_1024/BRAM64_1024.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM64_1024 || ORIG_REF_NAME==BRAM64_1024} -quiet] -quiet

# IP: bd/Top/ip/Top_auto_ds_0/Top_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_auto_ds_0 || ORIG_REF_NAME==Top_auto_ds_0} -quiet] -quiet

# IP: bd/Top/ip/Top_auto_pc_0/Top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_auto_pc_0 || ORIG_REF_NAME==Top_auto_pc_0} -quiet] -quiet

# XDC: ip/INS_RAM/INS_RAM_ooc.xdc

# XDC: ip/BRAM64_1024/BRAM64_1024_ooc.xdc

# XDC: ip/INS_RAM/INS_RAM_ooc.xdc

# XDC: ip/BRAM64_1024/BRAM64_1024_ooc.xdc

# XDC: bd/Top/Top_ooc.xdc
