# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_prime/polmul_prime.srcs/sources_1/ip/dsp_mul/dsp_mul.xci
# IP: The module: 'dsp_mul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_prime/polmul_prime.srcs/sources_1/ip/dsp_mul/dsp_mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_mul'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_prime/polmul_prime.srcs/sources_1/ip/dsp_mul/dsp_mul.xci
# IP: The module: 'dsp_mul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_prime/polmul_prime.srcs/sources_1/ip/dsp_mul/dsp_mul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_mul'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
