# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.BramSDPPropagationFix 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_prime/polmul_prime.cache/wt [current_project]
set_property parent.project_path D:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_prime/polmul_prime.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.2 [current_project]
set_property ip_output_repo d:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_prime/polmul_prime.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_Andrea/buffer_muxer.v
  D:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_Andrea/mod7681.v
  D:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_Andrea/parallel_Mults.v
  D:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_Andrea/poly_load_control_BRAM.v
  D:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_Andrea/s_mul.v
  D:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_Andrea/pol_mul256_parallel_in.v
}
read_ip -quiet d:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_prime/polmul_prime.srcs/sources_1/ip/dsp_mul/dsp_mul.xci
set_property used_in_implementation false [get_files -all d:/SABER_FPGA/Verilog_src/Polynomial_multiplier_prime/polmul_prime/polmul_prime.srcs/sources_1/ip/dsp_mul/dsp_mul_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top poly_mul256_parallel_in2 -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef poly_mul256_parallel_in2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file poly_mul256_parallel_in2_utilization_synth.rpt -pb poly_mul256_parallel_in2_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
